=== iten-engineering/xml-solution/04-DTD-Attribute/solution/directory.dtd
<!ENTITY % anrede "anrede (Herr | Frau) #IMPLIED">

<!ELEMENT directory (person)+>
<!ELEMENT person    (vorname, nachname)>
<!ATTLIST person    %anrede; >

<!ELEMENT vorname   (#PCDATA)> 
<!ELEMENT nachname  (#PCDATA)>

=== iten-engineering/xml-solution/04-DTD-Attribute/solution/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE directory SYSTEM "directory.dtd">
<directory>
  <person anrede="Frau">
    <vorname>Erika</vorname>
    <nachname>Wanner</nachname>
  </person>
  <person anrede="Frau">
    <vorname>Daniela</vorname>
    <nachname>Frischknecht</nachname>
  </person>
  <person anrede="Herr">
    <vorname>Klaus</vorname>
    <nachname>Leuenberger</nachname>
  </person>
</directory>
