=== iten-engineering/xml-solution/03-DTD-Elemente/solution/kunden.dtd
<!ELEMENT kunden 		(firma*)>
<!ELEMENT firma 		(name, adresse, kommunikation)>
<!ELEMENT adresse 		(strasse, plz, ort, land?)>
<!ELEMENT kommunikation (telefon, fax?, email)>

<!ELEMENT name 			(#PCDATA)>

<!ELEMENT strasse 		(#PCDATA)>
<!ELEMENT plz 			(#PCDATA)>
<!ELEMENT ort 			(#PCDATA)>
<!ELEMENT land 			(#PCDATA)>

<!ELEMENT telefon 		(#PCDATA)>
<!ELEMENT fax 			(#PCDATA)>
<!ELEMENT email 		(#PCDATA)>

=== iten-engineering/xml-solution/03-DTD-Elemente/solution/kunden.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kunden SYSTEM "kunden.dtd">
<kunden>
	<firma>
		<name>Aare Buchversand GmbH</name>
		<adresse>
			<strasse>Eigerweg 9</strasse>
			<plz>3006</plz>
			<ort>Bern</ort>
		</adresse>
		<kommunikation>
			<telefon>++41 (0)31 399 25 87</telefon>
			<fax>++41 (0)31 399 25 88</fax>
			<email>info@abv.ch</email>
		</kommunikation>
	</firma>
	<firma>
		<name>Bücher Scherz AG</name>
		<adresse>
			<strasse>Fröhlichstrasse 7</strasse>
			<plz>8000</plz>
			<ort>Zürich</ort>
			<land>Schweiz</land>
		</adresse>
		<kommunikation>
			<telefon>++41 (0)44 123 45 67</telefon>
			<email>office@scherz.ch</email>
		</kommunikation>
	</firma>
</kunden>
