=== iten-engineering/xml-solution/06-XML-Schema/solution/seminar.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="seminar">
		<xs:annotation>
			<xs:documentation>
				Schema Definition für das Seminar Beispiel
				mit starker Gliederung/Aufteilung der Elemente und Typen
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ziel" />
				<xs:element ref="datum" />
				<xs:element ref="zeitplan" />
				<xs:element ref="kursleiter" />
				<xs:element ref="teilnehmer" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ziel" type="xs:string" />

	<xs:element name="datum">
		<xs:complexType>
			<xs:attribute name="von" type="xs:date" use="required" />
			<xs:attribute name="bis" type="xs:date" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="zeitplan">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="lektion" />
				<xs:element ref="pause" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="lektion">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="thema" type="xs:string"
					maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attributeGroup ref="zeitAttrGroup" />
		</xs:complexType>
	</xs:element>

	<xs:element name="pause">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="zeitAttrGroup" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="kursleiter">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="person" type="personTyp"
					maxOccurs="2" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="teilnehmer">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="person" type="personTyp" minOccurs="3"
					maxOccurs="12" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="personTyp">
		<xs:sequence>
			<xs:element name="vorname" type="xs:string" minOccurs="0" />
			<xs:element name="nachname" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="anrede" type="anredeTyp" />
	</xs:complexType>

	<xs:simpleType name="anredeTyp">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Frau" />
			<xs:enumeration value="Herr" />
		</xs:restriction>
	</xs:simpleType>

	<xs:attributeGroup name="zeitAttrGroup">
		<xs:attribute name="von" type="xs:time" use="required" />
		<xs:attribute name="bis" type="xs:time" use="required" />
	</xs:attributeGroup>

</xs:schema>

=== iten-engineering/xml-solution/06-XML-Schema/solution/seminar.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seminar 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="seminar.xsd">

	<ziel>Einführung in XML</ziel>
	<datum von="2007-04-01" bis="2007-04-03" />
	<zeitplan>
		<lektion von="09:00:00" bis="12:30:00">
			<thema>Überblick</thema>
			<thema>eXtensible Markup Language</thema>
			<thema>Document Type Definition</thema>
		</lektion>
		<pause von="12:30:00" bis="13:30:00">Mittagessen</pause>
		<lektion von="13:30:00" bis="17:00:00">
			<thema>XML Schema</thema>
			<thema>Übungen</thema>
		</lektion>
	</zeitplan>
	<kursleiter>
		<person anrede="Herr">
		    <vorname>Peter</vorname>
    		<nachname>Meier</nachname>
		</person>
	</kursleiter>
	<teilnehmer>
		<person anrede="Herr">
		    <vorname>Eric</vorname>
    		<nachname>Balmer</nachname>
		</person>
		<person anrede="Frau">
		    <vorname>Linda</vorname>
    		<nachname>Mischler</nachname>
		</person>
		<person anrede="Frau">
		    <vorname>Brigitte</vorname>
    		<nachname>Bolli</nachname>
		</person>
		<person anrede="Herr">
		    <vorname>Alban</vorname>
    		<nachname>Fischer</nachname>
		</person>
	</teilnehmer>
</seminar>
